/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ADMIN_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ADMIN_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BOOKING_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CRON_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FACEBOOK_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MESSENGER_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MESSENGER_PAGE_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MESSENGER_VERIFY_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "META_CAPI_ACCESS_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "META_CAPI_DATASET_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "META_CAPI_TEST_EVENT_CODE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_FROM_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESEND_REPLY_TO": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}